name: Build and Upload Python Wheels

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    env:
      RELEASE_FILE: ${{ github.event.repository.name }}-${{ github.sha }}-py${{ matrix.python-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build wheel
      run: python -m build --wheel

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.RELEASE_FILE }}
        path: dist/
